### Matrices

- A matrix is a square array of numbers arranged into rows and columns.
- The numbers of rows and columns determine the *dimension* of the matrix.
- Matrices with one row or one column are also referred to as *vectors*.

To create a matrix in python, we use the matrix method from numpy.

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,2,3],[4,5,6]])
A

matrix([[1, 2, 3],
        [4, 5, 6]])

You can check the dimension of the matrix using:

In [3]:
A.shape

(2, 3)

To show some of the features here, we'll work with randomly generated matrices. The recommended way to generate random numbers in numpy is by creating a Generator object:

In [4]:
rng = np.random.default_rng(4350)

The value passed into the method above is the *seed*, whose purpose is to enable repeatibility later. You don't need to use it if you don't care about being able to generate the same set of random numbers later. After the previous step, you can generate random numbers from a wide range of distributions. The default is to use a uniform distribution. For instance,

In [5]:
A = rng.random((2, 3))
A

array([[0.67591613, 0.71727282, 0.31343354],
       [0.35701195, 0.35954397, 0.73862655]])

will generate a $2\times 3$ matrix with each element drawn from a uniform distribution from 0(inclusive) to 1(exclusive). For a standard normal distribution, you would do:

In [6]:
A = rng.normal(size=(2, 3))
A

array([[-0.80934359,  0.6927803 , -0.34126646],
       [ 1.03610346, -1.06396449,  0.33426782]])

As with other instances of normal distributions in numpy (and scipy.stats), you can use the *loc* and *scale* parameters when the mean and variance are different from their default values of 0 and 1. For a $t$-distribution with 10 degrees of freedom:

In [7]:
A = rng.standard_t(df = 10, size = (2, 3))
A

array([[-1.49411237,  2.99212124,  0.90912653],
       [ 2.18040239, -0.07987556,  0.69251805]])

You get the picture. For other distributions, check out doc at https://numpy.org/doc/stable/reference/random/generator.html. Here's a larger matrix:

In [8]:
A = rng.normal(size = (6, 4))
A

array([[ 0.75286076, -0.04357284,  0.94797273, -1.16052247],
       [ 1.92611264, -0.83959451,  0.4876906 ,  1.18779588],
       [-0.27256915,  0.25853973, -0.02667715, -0.09213138],
       [-2.03049391,  0.08123684,  1.92793833, -0.6038585 ],
       [ 1.78022766, -0.50019539,  0.30440467, -1.03754673],
       [ 1.47234151, -0.45497693,  0.68687117, -0.62338389]])

I'm assuming you're familiar with indexing from before. For instance, if you want to select just the second row or just the fourth column, of a slice of rows 2-3 and columns 1-2, and so on. One thing to be aware of is that the random number generator above returns an *ndarray*:

In [20]:
type(A)

numpy.ndarray

If you want a *matrix* instead, you will have to call numpy's matrix method.

In [21]:
A = np.matrix(rng.normal(size = (6, 4)))
type(A)

numpy.matrix

A matrix in numpy is just a special case of an array with two dimensions. There are a couple of advantages to this. One is that even a row or column vector will be identified as a matrix:

In [22]:
x = np.matrix([1, 2, 3, 4])
x.shape

(1, 4)

On the other hand, a row or column vector defined as an array will only have 1 dimension:

In [23]:
np.array([1, 2, 3, 4]).shape

(4,)

This will come in handy later. The other advantage relates to matrix multiplications, which we'll see soon. For now, let's get back to a few more basic matrix operations. It's sometimes useful to transpose a matrix:

In [29]:
A = np.matrix(rng.normal(size = (4, 2)))
A

matrix([[-0.64658024, -0.35239317],
        [ 1.94862999,  0.03062174],
        [-1.62690514,  1.5745716 ],
        [-0.01898836,  0.33320449]])

In [39]:
A.T

matrix([[-3.23085769,  0.76473041,  0.99770105],
        [-0.32760813,  0.27012219, -0.1458785 ],
        [ 0.81238842,  0.2358943 , -0.95445777]])

As long as two matrices are of the same shape, you can add them (element-wise):

In [33]:
B = np.matrix(rng.normal(size = (4, 2)))
B

matrix([[ 0.94255399,  0.41193875],
        [ 2.02810207,  0.14035849],
        [-0.50400848,  0.10395958],
        [-0.48850302,  1.08518546]])

In [34]:
A + B

matrix([[ 0.29597375,  0.05954559],
        [ 3.97673206,  0.17098023],
        [-2.13091361,  1.67853118],
        [-0.50749138,  1.41838995]])

The type of matrices we'll be working with are going to be **square** matrices, that is matrices with the same number of rows and columns:

In [36]:
A = np.matrix(rng.normal(size = (3, 3)))
A

matrix([[-3.23085769, -0.32760813,  0.81238842],
        [ 0.76473041,  0.27012219,  0.2358943 ],
        [ 0.99770105, -0.1458785 , -0.95445777]])

When you transpose a square matrix, you keep its shape:

In [40]:
A.T

matrix([[-3.23085769,  0.76473041,  0.99770105],
        [-0.32760813,  0.27012219, -0.1458785 ],
        [ 0.81238842,  0.2358943 , -0.95445777]])

Something interesting happens when you add a square matrix to its own transpose:

In [41]:
A + A.T

matrix([[-6.46171538,  0.43712228,  1.81008947],
        [ 0.43712228,  0.54024438,  0.0900158 ],
        [ 1.81008947,  0.0900158 , -1.90891554]])

Notice that the elements on the opposite sides of the diagonal are the same. This is a special type of matrix called a **symmetric** matrix and has enormous applications. Scalar multiplication works as expected:

In [42]:
# Multiplies each element of the matrix by 2
2 * A 

matrix([[-6.46171538, -0.65521627,  1.62477684],
        [ 1.52946083,  0.54024438,  0.4717886 ],
        [ 1.99540211, -0.291757  , -1.90891554]])

If you have two matrices $A$ and $B$, then a special operation available to them is **matrix multiplication**, which is only possible if *the number of columns of A = the number of rows of B*. The resulting matrix will have the number of rows and $A$ and the number of columns of $B$. For instance, if $A$ is a $3\times 4$ matrix, and $B$ is a $4\times 2$ matrix, then matrix multiplication is feasible, and the result is a $3\times 2$ matrix. We won't go into the depths of matrix multiplication here but here are a few basics.

If $x$ is a $1\times 3$ matrix and $y$ is a $3\times 1$ matrix, then the result of matrix multiplication between them is a $1\times 1$ matrix, which is just a number. This special case is also called a *dot product*.

In [43]:
x = np.matrix([1, 2, 3])
y = np.matrix([4, 5, 6]).T
x

matrix([[1, 2, 3]])

In [44]:
y

matrix([[4],
        [5],
        [6]])

In [45]:
# matrix multiplication
x * y

matrix([[32]])

Extending this concept, if $A$ is a $3\times 3$ matrix, then multiplying by $y$ above will yield a $3\times 1$ matrix:

In [46]:
A = np.matrix(rng.random(size=(3,3)))
A

matrix([[0.95649029, 0.87895095, 0.88793896],
        [0.25557622, 0.47504743, 0.19701771],
        [0.90502254, 0.24539179, 0.79665117]])

In [47]:
A * y

matrix([[13.54834965],
        [ 4.57964834],
        [ 9.62695611]])

What's happening here is that each row of $A$ is getting into a dot product with $y$. Each of those dot products results in a number. $A$ has 3 rows and so, the overall result is a matrix with 3 numbers. This is the extent to which we'll use matrix multiplication for now.

### Random Vectors

- Suppose $X_1, X_2, \ldots, X_n$ are random variables with means $\mu_1, \mu_2, \ldots, \mu_n$.
- It is convenient to represent this information in a matrix form. We define a *random vector* $\mathbf{X}$ as:
		$$ \mathbf{X}=(X_{1},\ldots,X_{n})^{T} $$
- Correspondingly, we define the expected value of the random vector as another vector:
$$
\begin{equation*}
\underset{n\times1}{\mathbf{\mu}}=E[\mathbf{X}]=\left(\begin{array}{c}
E[X_{1}]\\
\vdots\\
E[X_{n}]
\end{array}\right)=\left(\begin{array}{c}
\mu_{1}\\
\vdots\\
\mu_{n}
\end{array}\right)
\end{equation*}
$$

- And we define the *covariance matrix* as the matrix of variances and covariances arranged as:
$$
\begin{equation*}
\underset{n\times n}{\Sigma}=\left(\begin{array}{cccc}
\sigma_{1}^{2} & \sigma_{12} & \cdots & \sigma_{1n}\\
\sigma_{12} & \sigma_{2}^{2} & \cdots & \sigma_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
\sigma_{1n} & \sigma_{2n} & \cdots & \sigma_{n}^{2}
\end{array}\right)
\end{equation*}
$$

- We can also define a *correlation matrix* similarly:
$$
\begin{equation*}
\mathbf{C}=\left(\begin{array}{cccc}
1 & \rho_{12} & \cdots\  & \rho_{1n}\\
\rho_{12} & 1 & \cdots\  & \rho_{2n}\\
\vdots\  & \vdots\  & \ddots\  & \vdots\\
\rho_{1n} & \rho_{2n} & \cdots\  & 1
\end{array}\right)
\end{equation*}
$$

### Linear Combination of Random Variables: Matrix Edition

- Suppose $X_1$ and $X_2$ are random variables with means $1$ and $-1$, variances $4$ and $9$ and covariance $6$.
- Let's define two new random variables:
$$
	\begin{align*}
		Y_1 &= 2X_1 + 3X_2 \\
		Y_2 &= 2X_1 - 3X_2
	\end{align*}
$$
- Now let's calculate:
    - $E[Y_1]$
    - $E[Y_2]$
    - $\text{var}(Y_1)$
    - $\text{var}(Y_2)$
    - $\text{cov}(Y_1, Y_2)$
- These are much easier to solve in matrix form. We'll let $y_1$ and $y_2$ denote the coefficients of $Y_1$ and $Y_2$ in terms of the original random variables.

In [51]:
# Set up the mean vector:
mu = np.matrix([1, -1]).T
# Then the covariance matrix:
Sigma = np.matrix([[4, 6], [6, 9]])
# And finally the coefficients that represent the newly created random variables:
y1 = np.matrix([2, 3]).T
y2 = np.matrix([2, -3]).T

In [49]:
mu

matrix([[ 1],
        [-1]])

In [50]:
Sigma

matrix([[4, 6],
        [6, 9]])

In [52]:
y1

matrix([[2],
        [3]])

In [53]:
y2

matrix([[ 2],
        [-3]])

- Then, $E[Y_1] = y_1^T \cdot \mu$
- And $E[Y_2] = y_2^T \cdot \mu$

In [54]:
y1.T * mu

matrix([[-1]])

In [55]:
y2.T * mu

matrix([[5]])

- For the variance: $\text{var}(Y_1) = y_1^T \cdot \Sigma \cdot y_1$ 
- and $\text{var}(Y_2) = y_2^T \cdot \Sigma \cdot y_2$

In [56]:
y1.T * Sigma * y1

matrix([[169]])

In [57]:
y2.T * Sigma * y2

matrix([[25]])

- Finally, for the covariance: $\text{cov}(Y_1, Y_2) = y_1^T \cdot \Sigma \cdot y_2$

In [58]:
y1.T * Sigma * y2

matrix([[-65]])

This was a rather simple example, of course, but you can easily see how you can extend this to more than two random variables.